baseURL = "https://giuliacerripicologa.it"
languageCode = "it"
defaultContentLanguage = "it"
title = "Giulia Cerri | Psicologa Perinatale a Livorno"
theme = "portio"
enableRobotsTXT = true
canonifyURLs = false

[pagination]
  pagerSize = 6

DefaultContentLanguage = "it"

[sitemap]
  changefreq = "monthly"
  priority = 0.8
  filename = "sitemap.xml"

# Main Menu
[[menu.main]]
  name = "Home"
  url = "#home"
  weight = 1

[[menu.main]]
  name = "Servizi"
  url = "#support"
  weight = 2

[[menu.main]]
  name = "About"
  url = "#resume"
  weight = 3

[[menu.main]]
  name = "Contatti"
  url = "#contact"
  weight = 4

[params]
  logo = "images/site-navigation/logo.webp"
  footerLogo = "images/contact/widget-logo.webp"
  contactLink = "contact"
  blogPageURL = "blog"
  copyright = "All right reserved copyright © Giulia Cerri 2025"
  googleAnalytics = ""
  fabformURL = ""

  author = "Giulia Cerri"
  description = "Giulia Cerri è una Psicologa iscritta all'Ordine degli Psicologi della Toscana, specializzata in Psicologia Perinatale. Offre supporto psicologico individuale e di coppia a Livorno e online."
  keywords = "psicologa livorno, psicologia perinatale, supporto psicologico, gravidanza, post parto, psicologia online, psicologa toscana, giulia cerri psicologa"
  ogImage = "images/og-image.png"

[params.address]
  email = "giuliacerri.psicologa@gmail.com"
  phone = "+39 350 5904363"
  address = "Via Monte Grappa 6, Livorno | Online"
  openingHours = ""

[params.map]
  APIkey = ""
  latitude = ""
  longitude = ""
  pinImage = "images/pin.png"

# Social icons
[[params.social]]
  icon = "fa-instagram"
  url = "https://www.instagram.com/giuliacerri.psicologa"
  weight = 1

[[params.social]]
  icon = "fa-whatsapp"
  url = "https://wa.me/message/IKSE46XDXAZHE1"
  weight = 2

[[params.social]]
  icon = "fa-facebook"
  url = "https://www.facebook.com/profile.php?id=61585755094853"
  weight = 3

[[params.social]]
  icon = "fa-linkedin"
  url = "https://www.linkedin.com/in/giulia-cerri-823920337/"
  weight = 4

[[params.social]]
  icon = "fa-youtube"
  url = "https://youtube.com/@giuliacerripsicologa"
  weight = 5